/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectSchema extends BaseModel {
  static $columns = [
    'color',
    'createdAt',
    'id',
    'name',
    'sortOrder',
    'updatedAt',
    'userId',
  ] as const
  $columns = ProjectSchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TaskAssignmentSchema extends BaseModel {
  static $columns = ['assignedOn', 'createdAt', 'id', 'taskId', 'updatedAt'] as const
  $columns = TaskAssignmentSchema.$columns
  @column.date()
  declare assignedOn: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare taskId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TaskSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'estimatedPomodoros',
    'id',
    'isCompleted',
    'parentId',
    'priority',
    'projectId',
    'sortOrder',
    'title',
    'updatedAt',
    'userId',
  ] as const
  $columns = TaskSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare estimatedPomodoros: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCompleted: boolean
  @column()
  declare parentId: number | null
  @column()
  declare priority: number
  @column()
  declare projectId: number
  @column()
  declare sortOrder: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSettingSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'dailyPomoLimit',
    'id',
    'longBreakAfter',
    'longBreakMinutes',
    'pomoDurationMinutes',
    'shortBreakMinutes',
    'updatedAt',
    'userId',
    'workingDays',
  ] as const
  $columns = UserSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dailyPomoLimit: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare longBreakAfter: number
  @column()
  declare longBreakMinutes: number
  @column()
  declare pomoDurationMinutes: number
  @column()
  declare shortBreakMinutes: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare workingDays: any
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
