/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type CalendarTransformer from '#transformers/calendar_transformer'
import type ProjectTransformer from '#transformers/project_transformer'
import type SettingsTransformer from '#transformers/settings_transformer'
import type TaskTransformer from '#transformers/task_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Calendar = InferData<CalendarTransformer>
  export namespace Calendar {
    export type Variants = InferVariants<CalendarTransformer>
  }
  export type Project = InferData<ProjectTransformer>
  export namespace Project {
    export type Variants = InferVariants<ProjectTransformer>
  }
  export type Settings = InferData<SettingsTransformer>
  export namespace Settings {
    export type Variants = InferVariants<SettingsTransformer>
  }
  export type Task = InferData<TaskTransformer>
  export namespace Task {
    export type Variants = InferVariants<TaskTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
